# Generated by Django 4.0.3 on 2022-03-07 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('surname', models.CharField(db_index=True, max_length=255)),
                ('repertoire', models.IntegerField(verbose_name='reperotoire')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('file', models.FileField(upload_to='tracks/', verbose_name='file')),
                ('duration', models.TimeField(verbose_name='Duration')),
                ('published_date', models.DateField()),
                ('artists', models.ManyToManyField(to='qazmusic.artists')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='qazmusic.genres')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
            },
        ),
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poet', models.CharField(db_index=True, max_length=255, null=True)),
                ('composer', models.CharField(db_index=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True)),
                ('track_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qazmusic.tracks')),
            ],
        ),
        migrations.CreateModel(
            name='Charts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('number_of_tracks', models.ManyToManyField(to='qazmusic.tracks')),
            ],
        ),
    ]
