# Generated by Django 4.0.3 on 2022-03-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qazmusic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='repertoire',
            field=models.IntegerField(verbose_name='repertoire'),
        ),
    ]
