# Generated by Django 4.0.3 on 2022-03-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qazmusic', '0002_alter_artists_repertoire'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
