# Generated by Django 4.0.3 on 2022-03-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qazmusic', '0003_artists_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/photo/'),
        ),
    ]
