# Generated by Django 4.0.3 on 2022-03-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qazmusic', '0004_alter_artists_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artists',
            options={'verbose_name': 'Artist', 'verbose_name_plural': 'Artists'},
        ),
        migrations.AlterModelOptions(
            name='charts',
            options={'verbose_name': 'Chart', 'verbose_name_plural': 'Charts'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='lyrics',
            options={'verbose_name': 'Lyric', 'verbose_name_plural': 'Lyrics'},
        ),
    ]
