# Generated by Django 4.0.3 on 2022-03-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qazmusic', '0005_alter_artists_options_alter_charts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='surname',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
