# Generated by Django 4.0.3 on 2022-03-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qazmusic', '0006_alter_artists_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
    ]
