# Generated by Django 4.0.3 on 2022-03-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qazmusic', '0007_alter_artists_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracks',
            name='duration',
        ),
    ]
