# Generated by Django 4.0.3 on 2022-03-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qazmusic', '0008_remove_tracks_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charts',
            name='number_of_tracks',
            field=models.ManyToManyField(blank=True, to='qazmusic.tracks'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='artists',
            field=models.ManyToManyField(blank=True, to='qazmusic.artists'),
        ),
    ]
