# Generated by Django 4.0.3 on 2022-03-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qazmusic', '0009_alter_charts_number_of_tracks_alter_tracks_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='repertoire',
            field=models.IntegerField(null=True, verbose_name='repertoire'),
        ),
        migrations.AlterField(
            model_name='charts',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
