# Generated by Django 4.0.3 on 2022-03-08 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qazmusic', '0010_alter_artists_repertoire_alter_charts_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracks',
            name='artists',
        ),
        migrations.CreateModel(
            name='TracksArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qazmusic.artists')),
                ('track_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qazmusic.tracks')),
            ],
        ),
    ]
