# Generated by Django 4.0.3 on 2022-03-14 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qazmusic', '0011_remove_tracks_artists_tracksartist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qazmusic.artists'),
        ),
        migrations.AlterField(
            model_name='tracksartist',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qazmusic.artists'),
        ),
        migrations.AlterField(
            model_name='tracksartist',
            name='track_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qazmusic.tracks'),
        ),
    ]
