# Generated by Django 4.0.3 on 2022-05-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qazmusic', '0012_tracks_artist_alter_tracksartist_artist_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='photo',
            field=models.ImageField(default=True, upload_to='genres/'),
            preserve_default=False,
        ),
    ]
